### ISSUE TITLE
Error in  RepViz

### ISSUE THREAD

**Issue by bharati-mehani** [elolab/RepViz#1]
Hi @ThomasFaux and @elolab,

I am getting an error while running RepViz:
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 'coverage': In range 24: at least two out of 'start', 'end', and 'width', must be supplied.

This is how my input files look as shown in the attachment.
Can anybody please help to understand what does this error means and how to resolve this?

Thanks

<img width="1361" alt="Screen Shot 2021-03-11 at 7 09 37 PM" src="https://user-images.githubusercontent.com/47798557/110871997-7804f800-829d-11eb-9323-3aba1178c0c3.png">

**Comment by ThomasFaux** [comment]
Hello and thank you for using RepViz.

Can I please see the script you used along these input files?
Also can you show a test version of the BED_input and BAM_input so that I can verify the syntax.

**Comment by bharati-mehani** [comment]
Hi @ThomasFaux 
Thanks for the follow up.
I used the following code as suggested by your manual in order to check the highlighted region as shown in the attached figure.

`region <- GRanges("chr22:29967219-30126829")

RepViz::RepViz(region = region,
    genome = "hg19",
    BAM = "BAM_input.csv",
    BED = "BED_input.csv",
    avgTrack = TRUE,
    geneTrack = TRUE,
    verbose = FALSE)`

![highlighted_region](https://user-images.githubusercontent.com/47798557/111087494-56ec1380-84f8-11eb-8cce-d681cdb549ad.png)

Based on my region of interest as highlighted on IGV, this is how my consensus.bed looks like.
<img width="635" alt="1" src="https://user-images.githubusercontent.com/47798557/111092497-9a507d00-850c-11eb-8383-163236613572.png">

I will really appreciate your help.

**Comment by biobug16** [comment]
Hi Elolab/Repviz and Thomas Faux,
Here are my sample files.
But now a new error is arising with these set of files:

Error in plot.window(...) : need finite 'ylim' values

In addition: Warning message:

In max(as.numeric(names(table(unlist(coverages))))) :

  no non-missing arguments to max; returning -Inf

**Comment by bharati-mehani** [comment]
Hi Elolab/Repviz and Thomas Faux,
Here are my sample files.
But now a new error is arising with these set of files:

Error in plot.window(...) : need finite 'ylim' values
In addition: Warning message:
In max(as.numeric(names(table(unlist(coverages))))) : no non-missing
arguments to max; returning -Inf

I hope you can see the files here.

**Comment by ThomasFaux** [comment]
Hi, I will try to reproduce your error.

I will need the BAM_input.csv, BED_input.csv, consensus.bed files. Please send them to me by Email (faux.thomas1_at_gmail.com).

I also need you to copy paste me the full output with verbose=TRUE of what RepViz returns when you try to run the piece of code that you pasted earlier.

Last, I need you to copy paste me the result of sessionInfo().

With that I should be able to reproduce the error.

**Comment by biobug16** [comment]
Ok, I will do that. Kindly share your email address.

Thanks & Regards

**Comment by ThomasFaux** [comment]
So according to the bam files that you sent me I could reproduce both of the errors.

The first error you mentioned "error in evaluating the argument 'x' in selecting a method for function 'coverage': In range 24: at least two out of 'start', 'end', and 'width', must be supplied." 

This error is linked to the fact that there is some reads of poor value in the bam files. There are having a quality of zero, a length of zero, and some missing values. I didn't think about filtering that when I developed the software and this could be a lengthy update.
I suggest you try to circumvent this by trying to filter the bam files an plot them again.




The second error 
Error in plot.window(...) : need finite 'ylim' values
In addition: Warning message:
In max(as.numeric(names(table(unlist(coverages))))) : no non-missing
arguments to max; returning -Inf

It all boils down to the fact that the region that you are trying to plot is totally empty of reads. And the max value is defined to 0 by the software. You can circumvent that by setting the max and setting the avgTrack to FALSE. See following code.


region <- GRanges("chr22:29948934-29951059")


RepViz(region = region,
               genome = "hg19",
               BAM = "BAM_input.csv",
               BED = "BED_input.csv",
               avgTrack = FALSE,
               geneTrack = TRUE,
               verbose = TRUE,
               max = c(20,20))

![Rplot](https://user-images.githubusercontent.com/7881032/111230327-1bcd0b80-85f0-11eb-8b5e-d4767814d155.jpeg)

**Comment by bharati-mehani** [comment]
Thank you so much @ThomasFaux , I really appreciate your help. Filtering the bam actually worked.
I have another question about the figure legend. Is it possible if we can change the legend texts? Can you please guide with this too?

Thanks again

**Comment by ThomasFaux** [comment]
The way the legend is coded at the moment doesn't allow for a modification of the text for the BAM part, for the avgBAM and the BED part you can just modify the text in input file.

The software was developed with paired sample comparison in mind. I guess it would be a good idea to further develop the legend part and include more flexible way of putting the legend.

This won't come before a while tho.

I suggest you plot two separate legends for wt and mut using the regular legend() function and use the colour input of RepViz to make the colours of the legend match with the plotted colors. Keep in mind that at the moment both BAM panels are using the same colour input.
